--- # creating multiple users
- hosts: all
  become: yes

  tasks:
    - name: creating multiple user accounts
      user: name='{{item}}' state=present
      with_items:
        - Geetha
        - Ammu
        - Bhoomi
        - Sahasra
        
